tinymce.addI18n('indo',{
"Redo": "Ulang maju",
"Undo": "Ulang mundur",
"Cut": "Potong",
"Copy": "Salin",
"Paste": "Tempel",
"Select all": "Pilih semua",
"New document": "Buat baru",
"Ok": "Oke",
"Cancel": "Batal",
"Visual aids": "Bantuan visual",
"Bold": "Tebal",
"Italic": "Miring",
"Underline": "Garis bawah",
"Strikethrough": "Coret",
"Superscript": "Superscript",
"Subscript": "Subscript",
"Clear formatting": "Hapus format",
"Align left": "Rata kiri",
"Align center": "Rata tengah",
"Align right": "Rata kanan",
"Justify": "Rata penuh",
"Bullet list": "List butir",
"Numbered list": "List nomor",
"Decrease indent": "Kurangi indent",
"Increase indent": "Tambahi indent",
"Close": "Tututp",
"Formats": "Formater",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser Anda tidak mensupport salin langsung.",
"Headers": "Pilihan header",
"Header 1": "Header 1",
"Header 2": "Header 2",
"Header 3": "Header 3",
"Header 4": "Header 4",
"Header 5": "Header 5",
"Header 6": "Header 6",
"Headings": "Pilihan heading",
"Heading 1": "Heading 1",
"Heading 2": "Heading 2",
"Heading 3": "Heading 3",
"Heading 4": "Heading 4",
"Heading 5": "Heading 5",
"Heading 6": "Heading 6",
"Preformatted": "Tanpa format",
"Div": "Div",
"Pre": "Pre",
"Code": "Kode",
"Paragraph": "Paragraf",
"Blockquote": "Kutip",
"Inline": "Inline",
"Blocks": "Blocks",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.",
"Font Family": "Keluarga font",
"Font Sizes": "Ukuran font",
"Class": "Class",
"Browse for an image": "Pilih gambar",
"OR": "ATAU",
"Drop an image here": "Jatuhkan gambar ke sini",
"Upload": "Upload",
"Block": "Blok",
"Align": "Meluruskan",
"Default": "Standard",
"Circle": "Cirkel",
"Disc": "Disk",
"Square": "Kvadrat",
"Lower Alpha": "Lower Alpha",
"Lower Greek": "Lower Gr\u00e6sk",
"Lower Roman": "Lower Roman",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Anchor": "Anchor",
"Name": "Navn",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id b\u00f8r starte med et bogstav, efterfulgt af bogstaver, tal, bindestreger, punktummer, koloner eller underscores.",
"You have unsaved changes are you sure you want to navigate away?": "Du har ikke gemte \u00e6ndringer. Er du sikker p\u00e5 at du vil forts\u00e6tte?",
"Restore last draft": "Genopret sidste kladde",
"Special character": "Specielle tegn",
"Source code": "Kode sumber",
"Insert\/Edit code sample": "Masukkan kode program",
"Language": "Bahasa",
"Code sample": "Kode program",
"Color": "Warna",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Kiri ke kanan",
"Right to left": "Kanan ke kiri",
"Emoticons": "Emot-ikoner",
"Document properties": "Pengaturan dokumen",
"Title": "Judul",
"Keywords": "Kata kunci",
"Description": "Deskripsi",
"Robots": "Robotter",
"Author": "Forfatter",
"Encoding": "Kodning",
"Fullscreen": "Fuldsk\u00e6rm",
"Action": "Handling",
"Shortcut": "Genvej",
"Help": "Hj\u00e6lp",
"Address": "Adresse",
"Focus to menubar": "Fokus p\u00e5 menulinjen",
"Focus to toolbar": "Fokus p\u00e5 v\u00e6rkt\u00f8jslinjen",
"Focus to element path": "Fokuser p\u00e5 elementvej",
"Focus to contextual toolbar": "Fokuser p\u00e5 kontekstuelle v\u00e6rkt\u00f8jslinje",
"Insert link (if link plugin activated)": "Tambahkan link (jika plugin aktif)",
"Save (if save plugin activated)": "Gem (hvis save plugin er aktiveret)",
"Find (if searchreplace plugin activated)": "Find (hvis searchreplace plugin er aktiveret)",
"Plugins installed ({0}):": "Installerede plugins ({0}):",
"Premium plugins:": "Premium plugins:",
"Learn more...": "L\u00e6r mere...",
"You are using {0}": "Du benytter {0}",
"Plugins": "Plugins",
"Handy Shortcuts": "Praktiske Genveje",
"Horizontal line": "Garis horizontal",
"Insert\/edit image": "Masukkan atau ubah gambar",
"Image description": "Keterangan gambar",
"Source": "Sumber",
"Dimensions": "Dimensi",
"Constrain proportions": "Jaga proporsi",
"General": "Umum",
"Advanced": "Canggih",
"Style": "Gaya",
"Vertical space": "Lodret afstand",
"Horizontal space": "Vandret afstand",
"Border": "Kant",
"Insert image": "Masukkan gambar",
"Image": "Gambar",
"Image list": "Billede liste",
"Rotate counterclockwise": "Drej modsat urets retning",
"Rotate clockwise": "Drej med urets retning",
"Flip vertically": "Flip vertikalt",
"Flip horizontally": "Flip horisontalt",
"Edit image": "Rediger billede",
"Image options": "Billede indstillinger",
"Zoom in": "Zoom ind",
"Zoom out": "Zoom ud",
"Crop": "Besk\u00e6r",
"Resize": "Skaler",
"Orientation": "Retning",
"Brightness": "Lysstyrke",
"Sharpen": "G\u00f8r skarpere",
"Contrast": "Kontrast",
"Color levels": "Farve niveauer",
"Gamma": "Gamma",
"Invert": "Inverter",
"Apply": "Anvend",
"Back": "Tilbage",
"Insert date\/time": "Inds\u00e6t dato\/klokkeslet",
"Date\/time": "Dato\/klokkeslet",
"Insert link": "Masukkan link",
"Insert\/edit link": "Masukkan link",
"Text to display": "Teks tampilan",
"Url": "Url",
"Target": "Target",
"None": "Tiada",
"New window": "Jendela baru",
"Remove link": "Hapus link",
"Anchors": "Ankre",
"Link": "Link",
"Paste or type a link": "Inds\u00e6t eller skriv et link",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URLen som du angav ser ud til at v\u00e6re en email adresse. \u00d8nsker du at tilf\u00f8je det kr\u00e6vede prefiks  mailto: ?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URLen som du angav ser ud til at v\u00e6re et eksternt link. \u00d8nsker du at tilf\u00f8je det kr\u00e6vede prefiks http:\/\/ ?",
"Link list": "Link liste",
"Insert video": "Inds\u00e6t video",
"Insert\/edit video": "Masukkan video",
"Insert\/edit media": "Masukkan media",
"Alternative source": "Sumber alternatif",
"Poster": "Poster",
"Paste your embed code below:": "Masukkan kode sisipan:",
"Embed": "Sisip (embed)",
"Media": "Media",
"Nonbreaking space": "H\u00e5rdt mellemrum",
"Page break": "Pemisah halaman",
"Paste as text": "Inds\u00e6t som ren tekst",
"Preview": "Forh\u00e5ndsvisning",
"Print": "Udskriv",
"Save": "Gem",
"Find": "Find",
"Replace with": "Ganti dengan",
"Replace": "Ganti",
"Replace all": "Ganti semua",
"Prev": "Sebelumnya",
"Next": "Berikutnya",
"Find and replace": "Temukan dan ganti",
"Could not find the specified string.": "Kunne ikke finde s\u00f8getekst",
"Match case": "Tepat",
"Whole words": "Semua kata",
"Spellcheck": "Stavekontrol",
"Ignore": "Ignorer",
"Ignore all": "Ignorer alt",
"Finish": "F\u00e6rdig",
"Add to Dictionary": "Tilf\u00f8j til ordbog",
"Insert table": "Masukkan tabel",
"Table properties": "Pengaturan tabel",
"Delete table": "Hapus tabel",
"Cell": "Cell",
"Row": "Row",
"Column": "Kolom",
"Cell properties": "Pengaturan sel",
"Merge cells": "Gabung sel",
"Split cell": "Pisah sel",
"Insert row before": "Masukkan row sebelum",
"Insert row after": "Masukkan row sesudah",
"Delete row": "Hapus row",
"Row properties": "Pengaturan row",
"Cut row": "Potong row",
"Copy row": "Salin row",
"Paste row before": "Tempel row sebelum",
"Paste row after": "Tempel row sesudah",
"Insert column before": "Masukkan kolom sebelum",
"Insert column after": "Masukkan kolom sesudah",
"Delete column": "Hapus kolom",
"Cols": "Kolom",
"Rows": "Row",
"Width": "Lebar",
"Height": "Tinggi",
"Cell spacing": "Jarak sel",
"Cell padding": "Jarak padding sel",
"Caption": "Tulisan",
"Left": "Kiri",
"Center": "Tengah",
"Right": "Kanan",
"Cell type": "Tipe sel",
"Scope": "Skup",
"Alignment": "Tilpasning",
"H Align": "H juster",
"V Align": "V juster",
"Top": "Top",
"Middle": "Midt",
"Bottom": "Bund",
"Header cell": "Sidehoved celle",
"Row group": "R\u00e6kke gruppe",
"Column group": "Kolonne gruppe",
"Row type": "R\u00e6kke type",
"Header": "Sidehoved",
"Body": "Krop",
"Footer": "Sidefod",
"Border color": "Warna garis luar",
"Insert template": "Inds\u00e6t skabelon",
"Templates": "Skabeloner",
"Template": "Skabelon",
"Text color": "Warna teks",
"Background color": "Warna latar",
"Custom...": "Lainnya...",
"Custom color": "Warna lain",
"No color": "Ingen farve",
"Table of Contents": "Indholdsfortegnelse",
"Show blocks": "Vis klokke",
"Show invisible characters": "Vis usynlige tegn",
"Words: {0}": "Ord: {0}",
"{0} words": "{0} ord",
"File": "File",
"Edit": "Edit",
"Insert": "Masukkan",
"View": "Tampilan",
"Format": "Format",
"Table": "Tabel",
"Tools": "V\u00e6rkt\u00f8j",
"Powered by {0}": "Dipersembahkan oleh {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text omr\u00e5de. Tryk ALT-F9 for menu. Tryk ALT-F10 for toolbar. Tryk ALT-0 for hj\u00e6lp"
});